luksman v1.3.0

diff --git a/luksman b/luksman
--- a/luksman
+++ b/luksman
@@ -10,6 +10,8 @@
 # Installation, usage : https://github.com/rigou/luksman/blob/main/README.md
 # Run this script as root (sudo)
 
+set -o nounset
+
 readonly APPNAME='luksman'
 readonly VERSION='1.3.0'
 
@@ -468,7 +470,7 @@ function print_list {
 function exec_action {
 	local -i retval_int=0 # success
 	case "$Action" in
-	c) 	if [ "$(get_volume_status)" -eq $GVS_CLOSED ] ; then
+	"$ACT_CREATE") 	if [ "$(get_volume_status)" -eq $GVS_CLOSED ] ; then
 			create_luks
 			retval_int=$?
 		else
@@ -476,7 +478,7 @@ function exec_action {
 			retval_int=1
 		fi
 		;;
-	a)	if [ "$(get_volume_status)" -eq $GVS_CLOSED ] ; then
+	"$ACT_NEWKEY")	if [ "$(get_volume_status)" -eq $GVS_CLOSED ] ; then
 			add_or_replace_key
 			retval_int=$?
 		else
@@ -484,10 +486,10 @@ function exec_action {
 			retval_int=1
 		fi
 		;;
-	m) 	mount_luks ; retval_int=$? ;;
-	u)	unmount_luks ; retval_int=$? ;;
-	i)	print_info ; retval_int=0 ;;
-	l)	print_list ; retval_int=0 ;;
+	"$ACT_MOUNT") 	mount_luks ; retval_int=$? ;;
+	"$ACT_UMOUNT")	unmount_luks ; retval_int=$? ;;
+	"$ACT_INFO")	print_info ; retval_int=0 ;;
+	"$ACT_LIST")	print_list ; retval_int=0 ;;
 	esac
 	return $retval_int
 }
@@ -495,47 +497,46 @@ function exec_action {
 function usage {
 	print_line $stdin "$APPNAME v$VERSION usage"
 	local n0="    $APPNAME"
-	print_line $stdin "create volume in a file container or a device, optionally storing the key in a file"
-	print_line $stdin "$n0 -c name (-f folder -s size_MiB | -d device) [(-k keyfile_device | -K keyfile_disk_label)] -o owner_name "
+	print_line $stdin "create volume in a file container or a device"
+	print_line $stdin "$n0 $ACT_CREATE name (-f folder -s size_MiB | -d device) [(-k keyfile_device | -K keyfile_disk_label)] -o owner_name "
 	print_line $stdin "add or replace a key file"
-	print_line $stdin "$n0 -a name (-f folder | -d device) (-k keyfile_device | -K keyfile_disk_label)"
+	print_line $stdin "$n0 $ACT_NEWKEY name (-f folder | -d device) (-k keyfile_device | -K keyfile_disk_label)"
 	print_line $stdin "mount volume"
-	print_line $stdin "$n0 -m name (-f folder | -d device) [(-k keyfile_device | -K keyfile_disk_label)]"
+	print_line $stdin "$n0 $ACT_MOUNT name (-f folder | -d device) [(-k keyfile_device | -K keyfile_disk_label)]"
 	print_line $stdin "unmount volume"
-	print_line $stdin "$n0 -u name"
+	print_line $stdin "$n0 $ACT_UMOUNT name"
 	print_line $stdin "print volume information"
-	print_line $stdin "$n0 -i name"
+	print_line $stdin "$n0 $ACT_INFO name"
 	print_line $stdin "list mounted volumes"
-	print_line $stdin "$n0 -l"
+	print_line $stdin "$n0 $ACT_LIST"
 }
 
 function check_args {
 	local -i retval_int=1 # error
 	local -ri VOLUME_MIN_SIZE=17 # because LUKS takes a 16 MiB overhead
-	if [ "$Action" = 'l' ] ; then
+	if [ "$Action" = $ACT_LIST ] ; then
 		retval_int=0 # list takes no args
 	elif [ -n "$Name" ] ; then
 		# check required arguments
 		case "$Action" in
-		c) 	if [ -n "$Folder" ] && [ -z "$Device" ] && [ $Size -ge $VOLUME_MIN_SIZE ] && [ -n "$Owner" ] ; then retval_int=0 ; fi
+		"$ACT_CREATE") if [ -n "$Folder" ] && [ -z "$Device" ] && [ $Size -ge $VOLUME_MIN_SIZE ] && [ -n "$Owner" ] ; then retval_int=0 ; fi
 			if [ -n "$Device" ] && [ -z "$Folder" ] && [ -n "$Owner" ] ; then retval_int=0 ; fi
 			;;
-		a)	if [ -n "$Folder" ] && [ -z "$Device" ] && [ -n "$KeyDev" ] &&  [ -z "$KeyLabel" ] ; then retval_int=0 ; fi
+		"$ACT_NEWKEY") if [ -n "$Folder" ] && [ -z "$Device" ] && [ -n "$KeyDev" ] &&  [ -z "$KeyLabel" ] ; then retval_int=0 ; fi
 			if [ -n "$Folder" ] && [ -z "$Device" ] && [ -z "$KeyDev" ] &&  [ -n "$KeyLabel" ] ; then retval_int=0 ; fi
 			if [ -n "$Device" ] && [ -z "$Folder" ] && [ -n "$KeyDev" ] &&  [ -z "$KeyLabel" ] ; then retval_int=0 ; fi
 			if [ -n "$Device" ] && [ -z "$Folder" ] && [ -z "$KeyDev" ] &&  [ -n "$KeyLabel" ] ; then retval_int=0 ; fi
 			;;
-		m)	if [ -n "$Folder" ] && [ -z "$Device" ] ; then retval_int=0 ; fi
+		"$ACT_MOUNT") if [ -n "$Folder" ] && [ -z "$Device" ] ; then retval_int=0 ; fi
 			if [ -n "$Device" ] && [ -z "$Folder" ] ; then retval_int=0 ; fi
 			;;
-		u)	retval_int=0 ;;
-		i)	retval_int=0 ;;
+		"$ACT_UMOUNT" | "$ACT_INFO") retval_int=0 ;;
 		esac
 		if [ $retval_int -eq 0 ] ; then
 			# check optional arguments -k -K
 			if [ -n "$KeyDev" ] && [ -n "$KeyLabel" ] ; then retval_int=1 ; fi
 			if [ -n "$KeyDev" ] || [ -n "$KeyLabel" ] ; then
-				if [ "$Action" = 'u' ] || [ "$Action" = 'i' ] ; then
+				if [ "$Action" = "$ACT_UMOUNT" ] || [ "$Action" = "$ACT_INFO" ] ; then
 					retval_int=1
 				fi
 			fi
@@ -566,16 +567,27 @@ if [ "$(id -u)" != '0' ] ; then
 	exit 1
 fi
 
-# change to user's home dir in order to prevent errors like
-# "find: Failed to restore initial working directory: /mnt/sshfs/enigma:59607/home/rigou/bin/backup: Permission denied"
-# as a result, the -f folder option should specify an absolute path, or a path relative to the home dir
-if ! cd "/home/${SUDO_USER:-$USER}" ; then
-	print_line $stderr "WARNING: working directory is $(pwd)"
+# Parse command line args
+if [ $# -eq 0 ] ; then
+	usage
+	exit 1
 fi
 
-# Parse CLI options
-declare Action=''
-declare Name=''
+# parse positional args
+readonly ACT_CREATE='create'
+readonly ACT_NEWKEY='newkey'
+readonly ACT_MOUNT='mount'
+readonly ACT_UMOUNT='umount'
+readonly ACT_INFO='info'
+readonly ACT_LIST='list'
+declare Action=$1
+declare Name='' # empty if Action=ACT_LIST
+if [ $# -ge 2 ] ; then
+	Name=$2
+fi
+shift 2
+
+# parse optional args
 declare Folder=''
 declare -i Size=0
 declare Device=''
@@ -583,11 +595,9 @@ declare Owner=''
 declare KeyDev=''
 declare KeyLabel=''
 if [ $# -ne 0 ] ; then
-	while getopts c:a:m:u:i:f:s:d:o:k:K:l option
+	while getopts f:s:d:o:k:K: option
 	do
 		case $option in
-		c | a | m | u | i ) Action=$option ; Name=$OPTARG ;;
-		l) Action=$option ; Name='' ;;
 		f) Folder=$OPTARG ;;
 		s) Size=$OPTARG ;;
 		d) Device=$OPTARG ;;
@@ -598,14 +608,19 @@ if [ $# -ne 0 ] ; then
 		esac
 	done
 	shift $((OPTIND -1)) 
-else
-	usage
-	exit 1
 fi
 
 # Initializations
 declare -i Exitval=0
-if [ -n "$Name" ] ; then # the list action takes no args, hence Name is empty
+
+# change to user's home dir in order to prevent errors like
+# "find: Failed to restore initial working directory: /mnt/sshfs/enigma:59607/home/rigou/bin/backup: Permission denied"
+# as a result, the -f folder option should specify an absolute path, or a path relative to the home dir
+if ! cd "/home/${SUDO_USER:-$USER}" ; then
+	print_line $stderr "WARNING: working directory is $(pwd)"
+fi
+
+if [ -n "$Name" ] ; then # ACT_LIST takes no args, hence Name is empty
 	readonly DevMountPoint="/tmp/$APPNAME.dev"
 	readonly KeyMountPoint="/tmp/$APPNAME.key"
 	readonly LuksMountPoint="/mnt/$APPNAME/$Name"
