fixed check_args(), implemented SIGINT in create_luks(), mod create_temp_keyfile() to work in /tmp

diff --git a/luksman b/luksman
--- a/luksman
+++ b/luksman
@@ -30,6 +30,15 @@ function print_line {
 	esac
 }
 
+# 	Proper handling of SIGINT/SIGQUIT http://www.cons.org/cracauer/sigint.html
+# 	Take no action when SIGINT is received while you wait for a child. Make a note of the fact that you did receive it, though. 
+declare -i ExitSignalReceived=0
+function interruption {
+	print_line $stderr "exiting"
+	ExitSignalReceived=1
+}
+trap 'interruption' SIGINT SIGTERM SIGQUIT
+
 # Trim leading and trailing whitespace from given text
 function inc_Trim {
     local text=$1
@@ -60,12 +69,15 @@ function sanitize_name {
 }
 
 function get_temp_keyfile {
-	echo "$KeyFile.tmp"
+	echo "$AppTmpDir/$(basename "$KeyFile").tmp"
 }
 
 function validate_temp_keyfile {
 	print_line $stdout "validating new key file"
-	mv -f "$(get_temp_keyfile)" "$KeyFile"
+	mkdir -p "$(dirname "$KeyFile")"
+	# mv issues a warning when target is Fat/exFat filesystem, but returns 0 anyway
+	# "mv: failed to preserve ownership : Operation not permitted"
+	mv -f "$(get_temp_keyfile)" "$KeyFile" 2>/dev/null
 	return $?
 }
 
@@ -76,20 +88,26 @@ function validate_temp_keyfile {
 # Lucks will use our key to unlock the master-key of the encrypted device
 # (passphrases can be up to 512 characters and keyfiles up to 8192 KiB)
 function create_temp_keyfile {
-	#print_line $stdebug "create_temp_keyfile()"
+	print_line $stdebug "create_temp_keyfile()"
 	local -i retval=0 # success
 	local temp_keyfile ; temp_keyfile=$(get_temp_keyfile)
 	print_line $stdout "generating new key file"
 	local key ; key=$(LC_ALL=C tr -dc 'A-Za-z0-9_\+\-*/=,?;.:/!$&#{[|]}@%&$"~^' < /dev/random | head -c 33)
-	mkdir -p "$(dirname "$temp_keyfile")"
 	if ! echo -n "$key" >"$temp_keyfile" ; then
 		retval=1 # error
 	fi
+	chown "$USERNAME": "$temp_keyfile"
 	return $retval
 }
 
+function delete_temp_keyfile {
+	print_line $stdebug "deleting temporary key file"
+	rm -f "$(get_temp_keyfile)"
+	return $?
+}
+
 function mount_key {
-	#print_line $stdebug "mount_key()"
+	print_line $stdebug "mount_key()"
 	local -i retval=0 # 0=success, 1=error
 	if ! mountpoint -q "$KeyDevMountPoint" ; then
 		mount "$KeyDev" "$KeyDevMountPoint"
@@ -99,10 +117,10 @@ function mount_key {
 }
 
 function unmount_key {
-	#print_line $stdebug "unmount_key()"
+	print_line $stdebug "unmount_key()"
 	local -i retval=0 # 0=success, 1=error
 	if mountpoint -q "$KeyDevMountPoint" ; then
-		rm -f "$(get_temp_keyfile)" # just in case
+		delete_temp_keyfile # just in case
 		umount "$KeyDevMountPoint"
 		retval=$?
 	else
@@ -119,7 +137,7 @@ function unmount_key {
 # if given label, uuid and device are invalid or empty, print nothing
 # Return value : 0=success, 1=error
 function get_disk_device {
-	#print_line $stdebug "get_disk_device()"
+	print_line $stdebug "get_disk_device()"
 	local -i retval=1 # 0=success, 1=error
 	local disk_id=$1 # either label or uuid or /dev/sdxy
 	if [ -n "$disk_id" ] ; then
@@ -150,14 +168,14 @@ function get_disk_device {
 # print the path of the container file of attached volume name
 # or nothing if none (volume resides in a disk partition, or is not attached, or does not exist)
 function get_container_file {
-	#print_line $stdebug "get_container_file()"
+	print_line $stdebug "get_container_file()"
 	losetup --output BACK-FILE --noheadings |grep "/$1.dat"
 }
 
 # print the loop device of attached volume name
 # or nothing if none (volume resides in a disk partition, or is not attached, or does not exist)
 function get_loop_device {
-	#print_line $stdebug "get_loop_device()"
+	print_line $stdebug "get_loop_device()"
 	local container_file=''
 	container_file=$(get_container_file "$1")
 	if [ -n "$container_file" ] ; then
@@ -168,7 +186,7 @@ function get_loop_device {
 # Tell if given volume name corresponds to an attached loop device
 # Return value: 0=attached, 1=not attached or not a loop device
 function is_attached_container_file {
-	#print_line $stdebug "is_attached_container_file()"
+	print_line $stdebug "is_attached_container_file()"
 	local -i retval=0
 	if [ -z "$(get_loop_device "$1")" ] ; then
 		retval=1
@@ -182,7 +200,7 @@ declare -ir GVS_MOUNTED=1	# encrypted filesystem mounted, ready for use
 declare -ir GVS_FAILED1=2	# container file attached (if any), no LUKS open
 declare -ir GVS_FAILED2=3	# container file attached (if any) and LUKS open but filesystem not mounted
 function get_volume_status {
-	#print_line $stdebug "get_volume_status()"
+	print_line $stdebug "get_volume_status()"
 	local -i retval=$GVS_CLOSED
 	local -i attached_bool=0 # 0=false, 1=true
 	local -i luksopen_bool=0
@@ -209,7 +227,7 @@ function get_volume_status {
 }
 
 function print_volume_status {
-	#print_line $stdebug "print_volume_status()"
+	print_line $stdebug "print_volume_status()"
 	local -i status ; status=$(get_volume_status)
 	local open_text=''
 	case $status in
@@ -229,10 +247,10 @@ function print_volume_status {
 
 # return value: writes the device name on stdout, or 'ERROR'
 function attach_container_file {
-	#print_line $stdebug "attach_container_file()"
+	print_line $stdebug "attach_container_file()"
 	if [ -f "$ContainerFile" ] ; then
 		if ! is_attached_container_file "$Name" ; then
-			#print_line $stdebug "attaching $ContainerFile"
+			print_line $stdebug "attaching $ContainerFile"
 			# The loop device setup is not an atomic operation when used with --find, 
 			# and losetup does not protect this operation by any lock.
 			# It is recommended to use flock(1) to avoid a collision in heavily parallel use cases
@@ -266,10 +284,10 @@ function attach_container_file {
 }
 
 function detach_container_file {
-	#print_line $stdebug "detach_container_file()"
-	retval=0 # success
+	print_line $stdebug "detach_container_file()"
+	local retval=0 # success
 	if is_attached_container_file "$Name" ; then
-		#print_line $stdebug "detaching $(get_container_file "$Name")"
+		print_line $stdebug "detaching $(get_container_file "$Name")"
 		local luks_dev=''
 		luks_dev=$(get_loop_device "$Name")
 		if [ -n "$luks_dev" ] ; then
@@ -286,13 +304,14 @@ function detach_container_file {
 }
 
 function create_luks {
-	#print_line $stdebug "create_luks()"
+	print_line $stdebug "create_luks()"
 	local -i retval=0 # success
 	local luks_dev=''
 	local -i attached_bool=0 # 0=false, 1=true
 	local -i luksopen_bool=0 # 0=false, 1=true
 	local -i keydev_mounted_bool=0 # 0=false, 1=true
-
+	local -i new_container_file_bool=0 # 1=a new file has been created here and we may remove it if some error happens during the creation process
+	
 	# test for existing container file with same name
 	if [ -n "$ContainerFile" ] && [ -f "$ContainerFile" ] ; then
 		print_line $stderr "can not create volume $Name because file $ContainerFile already exists"
@@ -332,12 +351,16 @@ function create_luks {
 				'YES') retval=0 ;;
 				*) retval=1 ;;
 			esac
+			if [ $ExitSignalReceived -eq 1 ] ; then
+				retval=1 # user sent SIGINT
+			fi
 		fi
 	fi
 
 	if [ $retval -eq 0 ] ; then
 		if [ -n "$ContainerFile" ] ; then
 			print_line $stdout "assigning $ContainerFile to $USERNAME"
+			new_container_file_bool=1
 			touch "$ContainerFile"
 			chown "$USERNAME": "$ContainerFile" 2>/dev/null # silently fails with Fat/exFat filesystems
 			print_line $stdout "filling $ContainerFile with $Size MB random data"
@@ -349,7 +372,7 @@ function create_luks {
 					retval=1 # error
 				fi
 			else
-				retval=1 # error
+				retval=1 # error or user sent SIGINT
 			fi
 			sync
 		else
@@ -368,7 +391,7 @@ function create_luks {
 						retval=1 # error
 					fi
 				else
-					retval=1 # error
+					retval=1 # error or user sent SIGINT
 				fi
 			else
 				retval=1 # error
@@ -382,11 +405,11 @@ function create_luks {
 					retval=1 # error
 				fi
 			else
-				retval=1 # error
+				retval=1 # error or user sent SIGINT
 			fi
 		fi
 	fi
-
+	
 	if [ $retval -eq 0 ] ; then
 		if mkfs -t ext4 -L "$Name" "$LuksMap" ; then
 			print_line $stdout "assigning $Name to $USERNAME"
@@ -401,22 +424,34 @@ function create_luks {
 			retval=1 # error
 		fi
 	fi
-
+	
 	if [ $luksopen_bool -eq 1 ] ; then
 		cryptsetup close "$LuksMap"
 	fi
+	
 	if [ $attached_bool -eq 1 ] ; then
 		detach_container_file
 	fi
-	if [ -n "$KeyDev" ] ; then
-		if [ $retval -eq 0 ] ; then
-			validate_temp_keyfile
-			retval=$?
+
+	if [ $retval -ne 0 ] ; then 
+		if [ $new_container_file_bool -eq 1 ] && [ -f "$ContainerFile" ] ; then
+			print_line $stdout "deleting container file"
+			rm -f "$ContainerFile"
+		fi
+		if [ -n "$KeyDev" ] && [ -f "$(get_temp_keyfile)" ] ; then
+			delete_temp_keyfile
 		fi
 	fi
+
+	if [ $retval -eq 0 ] && [ -n "$KeyDev" ] ; then
+		validate_temp_keyfile
+		retval=$?
+	fi
+	
 	if [ $keydev_mounted_bool -eq 1 ] ; then
 		unmount_key
 	fi
+	
 	if [ $retval -eq 0 ] ; then
 		print_line $stdout "volume $Name is created"
 	fi
@@ -424,7 +459,7 @@ function create_luks {
 }
 
 function newkey_luks {
-	#print_line $stdebug "newkey_luks()"
+	print_line $stdebug "newkey_luks()"
 	local -i retval=0 # success
 	local luks_dev=''
 	local -i attached_bool=0 # 0=false, 1=true
@@ -487,7 +522,7 @@ function newkey_luks {
 }
 
 function mount_luks {
-	#print_line $stdebug "mount_luks()"
+	print_line $stdebug "mount_luks()"
 	local -i retval=0 # success
 	local -i key_mounted_bool=0 # 0=false 1=true
 	if [ -n "$KeyDev" ] ; then
@@ -540,7 +575,7 @@ function mount_luks {
 
 # unmounting an encrypted volume is a 3 steps process
 function unmount_luks {
-	#print_line $stdebug "unmount_luks()"
+	print_line $stdebug "unmount_luks()"
 	local -i retval=0 # success
 	local -i status=0; status=$(get_volume_status)
 
@@ -555,29 +590,29 @@ function unmount_luks {
 			# list open files, if any
 			lsof +d "$LuksMountPoint" 2>/dev/null ; retval=1
 			retval=1 # error
-			#print_line $stdebug "unmount_luks() failed, error $retval"
+			print_line $stdebug "unmount_luks() failed, error $retval"
 		fi
 		print_volume_status
 		;;
 
 	"$GVS_FAILED2") # unmount step 2 : container file attached (if any) and LUKS open but filesystem not mounted
-		#print_line $stdebug "closing $LuksMap"
+		print_line $stdebug "closing $LuksMap"
 		if cryptsetup close "$LuksMap" ; then
 			unmount_luks # recursive call to case GVS_FAILED1
 			retval=$?
 		else
 			retval=2 # error
-			#print_line $stdebug "unmount_luks() failed, error $retval"
+			print_line $stdebug "unmount_luks() failed, error $retval"
 		fi
 		;;
 
 	"$GVS_FAILED1") # unmount step 3 : container file attached, no LUKS open
-		#print_line $stdebug "detaching $LuksMap"
+		print_line $stdebug "detaching $LuksMap"
 		if detach_container_file ; then
 			retval=0
 		else
 			retval=3 # error
-			#print_line $stdebug "unmount_luks() failed, error $retval"
+			print_line $stdebug "unmount_luks() failed, error $retval"
 		fi
 		;;
 
@@ -590,7 +625,7 @@ function unmount_luks {
 }
 
 function delete_luks {
-	#print_line $stdebug "delete_luks()"
+	print_line $stdebug "delete_luks()"
 	local -i retval=0 # success
 
 	if [ "$(get_volume_status)" -eq $GVS_CLOSED ] ; then
@@ -675,7 +710,7 @@ function delete_luks {
 }
 
 function print_list {
-	#print_line $stdebug "print_list()"
+	print_line $stdebug "print_list()"
 	local path=''
 	find /dev/mapper -type l -print0 |while IFS= read -r -d '' path
 	do
@@ -695,7 +730,7 @@ function print_list {
 }
 
 function exec_action {
-	#print_line $stdebug "exec_action($Action)"
+	print_line $stdebug "exec_action($Action)"
 	local -i retval=0 # success
 	case "$Action" in
 	"$ACT_CREATE") if [ "$(get_volume_status)" -eq $GVS_CLOSED ] ; then
@@ -759,7 +794,7 @@ function usage {
 }
 
 function check_args {
-	#print_line $stdebug "check_args($Action $Name)"
+	print_line $stdebug "check_args($Action $Name)"
 	local -i retval=1 # error
 	local -ri VOLUME_MIN_SIZE=17 # because LUKS takes a 16 MB overhead
 	if [ "$Action" = $ACT_LIST ] ; then
@@ -771,19 +806,19 @@ function check_args {
 			# check required arguments
 			case "$Action" in
 			"$ACT_CREATE")
-				if [ -n "$Folder" ] && [ -z "$BlockDev" ] && [ $Size -ge $VOLUME_MIN_SIZE ] ; then retval=0 ; fi
-				if [ -n "$BlockDev" ] && [ -z "$Folder" ] ; then retval=0 ; fi
+				if [ -n "$Folder" ] && [ -z "$BlockDisk" ] && [ $Size -ge $VOLUME_MIN_SIZE ] ; then retval=0 ; fi
+				if [ -n "$BlockDisk" ] && [ -z "$Folder" ] ; then retval=0 ; fi
 				;;
 			"$ACT_NEWKEY")
-				if [ -n "$Folder" ] && [ -z "$BlockDev" ] ; then retval=0 ; fi
-				if [ -z "$Folder" ] && [ -n "$BlockDev" ] ; then retval=0 ; fi
+				if [ -n "$Folder" ] && [ -z "$BlockDisk" ] ; then retval=0 ; fi
+				if [ -z "$Folder" ] && [ -n "$BlockDisk" ] ; then retval=0 ; fi
 				;;
 			"$ACT_MOUNT" | "$ACT_DELETE")
-				if [ -n "$Folder" ] && [ -z "$BlockDev" ] ; then retval=0 ; fi
-				if [ -n "$BlockDev" ] && [ -z "$Folder" ] ; then retval=0 ; fi
+				if [ -n "$Folder" ] && [ -z "$BlockDisk" ] ; then retval=0 ; fi
+				if [ -n "$BlockDisk" ] && [ -z "$Folder" ] ; then retval=0 ; fi
 				;;
 			"$ACT_UNMOUNT" | "$ACT_LIST")
-				if [ -z "$Folder" ] && [ -z "$BlockDev" ] && [ -z "$KeyDev" ] && [ $Size -eq 0 ] ; then retval=0 ; fi
+				if [ -z "$Folder" ] && [ -z "$BlockDisk" ] && [ -z "$KeyDisk" ] && [ $Size -eq 0 ] ; then retval=0 ; fi
 				;;
 			esac
 			if [ $retval -ne 0 ] ; then 
@@ -796,8 +831,8 @@ function check_args {
 	fi
 	if [ $retval -eq 0 ] ; then 
 		if [ -n "$Folder" ] && ! [ -d "$Folder" ] ; then print_line $stderr "folder $Folder not found" ; retval=2 ; fi
-		if [ -n "$BlockDev" ] && ! [ -b "$BlockDev" ] ; then print_line $stderr "device $BlockDisk not found" ; retval=2 ; fi
-		if [ -n "$KeyDev" ] && ! [ -b "$KeyDev" ] ; then print_line $stderr "device $KeyDisk not found" ; retval=2 ; fi
+		if [ -n "$BlockDisk" ] && ! [ -b "$BlockDev" ] ; then print_line $stderr "device $BlockDisk not found" ; retval=2 ; fi
+		if [ -n "$KeyDisk" ] && ! [ -b "$KeyDev" ] ; then print_line $stderr "device $KeyDisk not found" ; retval=2 ; fi
 	fi
 	return $retval
 }
@@ -810,7 +845,7 @@ if [ "$(id -u)" != '0' ] ; then
 fi
 readonly USERNAME=${SUDO_USER:-$USER} # get the underlying user logname (the one running sudo)
 
-#print_line $stdebug "$(date '+%Y%m%dT%H%M') $(basename "$0" '.sh') $* (pid=$$)"
+print_line $stdebug "$(date '+%Y%m%dT%H%M') $(basename "$0" '.sh') $* (pid=$$)"
 
 # Parse command line args
 readonly ACT_CREATE='create'
@@ -866,9 +901,12 @@ if ! cd "/home/${SUDO_USER:-$USER}" ; then
 	print_line $stderr "WARNING: working directory is $(pwd)"
 fi
 
+readonly AppTmpDir="/tmp/$APPNAME-$$"
+mkdir $AppTmpDir || exit 1
+
 if [ -n "$Name" ] ; then # ACT_LIST takes no args, hence Name is empty
-	readonly BlockDevMountPoint="/tmp/$APPNAME-$$.dev"
-	readonly KeyDevMountPoint="/tmp/$APPNAME-$$.key"
+	readonly BlockDevMountPoint="$AppTmpDir/dev"
+	readonly KeyDevMountPoint="$AppTmpDir/key"
 	readonly LuksMountPoint="/mnt/$APPNAME/$Name"
 	readonly LuksMap="/dev/mapper/$Name"
 	declare ContainerFile=''
@@ -919,8 +957,11 @@ if check_args ; then
 			rmdir "$LuksMountPoint" 
 		fi
 	fi
-	#print_line $stdebug "$(date '+%Y%m%dT%H%M') $(basename "$0" '.sh') $* (pid=$$) EXIT $Exitval"
-	exit $Exitval
 else
-	exit 1
+	Exitval=1
 fi
+
+rmdir $AppTmpDir
+
+print_line $stdebug "$(date '+%Y%m%dT%H%M') $(basename "$0" '.sh') $* (pid=$$) EXIT $Exitval"
+exit $Exitval
